# Generated by Django 4.1.7 on 2023-02-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
